INFO - 2023-06-16 16:42:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-16 16:42:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-16 16:42:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-16 16:42:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-16 16:42:47 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\Grao-Bristo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Grao-Bristo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('127.0.0.1', 'root', '', 'GraoBristo', 3346, '', 0)
#1 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Grao-Bristo\app\Views\Cardapio.php(20): CodeIgniter\Database\BaseConnection->query('SELECT DISTINCT...')
#4 C:\xampp\htdocs\Grao-Bristo\system\View\View.php(213): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\Grao-Bristo\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\Grao-Bristo\system\Common.php(1184): CodeIgniter\View\View->render('Cardapio', Array, true)
#7 C:\xampp\htdocs\Grao-Bristo\app\Controllers\Home.php(128): view('Cardapio', Array)
#8 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(934): App\Controllers\Home->Cardapio()
#9 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Grao-Bristo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\Grao-Bristo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Grao-Bristo\app\Views\Cardapio.php(20): CodeIgniter\Database\BaseConnection->query('SELECT DISTINCT...')
#3 C:\xampp\htdocs\Grao-Bristo\system\View\View.php(213): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\Grao-Bristo\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\Grao-Bristo\system\Common.php(1184): CodeIgniter\View\View->render('Cardapio', Array, true)
#6 C:\xampp\htdocs\Grao-Bristo\app\Controllers\Home.php(128): view('Cardapio', Array)
#7 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(934): App\Controllers\Home->Cardapio()
#8 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Grao-Bristo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-16 16:42:47 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Views\Cardapio.php(20): CodeIgniter\Database\BaseConnection->query('SELECT DISTINCT Tipo FROM item')
 3 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\Grao-Bristo\\app\\Views\\Cardapio.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('Cardapio', [], true)
 6 APPPATH\Controllers\Home.php(128): view('Cardapio', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->Cardapio()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-06-16 16:42:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-16 16:42:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-06-16 16:45:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-06-16 16:45:57 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\Grao-Bristo\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Grao-Bristo\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('127.0.0.1', 'root', '', 'GraoBristo', 3346, '', 0)
#1 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Cl...', Array, false)
#4 C:\xampp\htdocs\Grao-Bristo\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Grao-Bristo\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Grao-Bristo\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Grao-Bristo\app\Controllers\Usuarios.php(96): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(934): App\Controllers\Usuarios->CadastrarCliente()
#9 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Grao-Bristo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\Grao-Bristo\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Grao-Bristo\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Cl...', Array, false)
#3 C:\xampp\htdocs\Grao-Bristo\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Grao-Bristo\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Grao-Bristo\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\Grao-Bristo\app\Controllers\Usuarios.php(96): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(934): App\Controllers\Usuarios->CadastrarCliente()
#8 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#9 C:\xampp\htdocs\Grao-Bristo\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Grao-Bristo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-06-16 16:45:57 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Cliente` (`Nome`, `Senha`) VALUES (:Nome:, :Senha:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Usuarios.php(96): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Usuarios->CadastrarCliente()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
